env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/essential'
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {
  import/no-cycle: off # due to bad design of PanJiaChen/vue-element-admin which has cyclic dependency
}
settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'
